version: '3'

tasks:
  default:
  generate:
    aliases: ["gen"]
    cmds:
      - protoc --go_out=./gen/ --go_opt=paths=source_relative --go-grpc_out=./gen/ --go-grpc_opt=paths=source_relative protos/todo/todo.proto